# {{$dotenv ...}} references values in file ./.env
# authorization assumes that app touter v22 is in use (may also work with v21)
# Run ./get-tokens.sh first to populate token= and mtx_token= in .env

@domain={{$dotenv domain}}
@tenant_id={{$dotenv tenant_id_2}}

### Actually it doesn't matter which tenant_host is used. All requests are routed
###  to the app router, and the actual tenant is obtained from the token.
@tenant_host={{$dotenv tenant_host}}
@mtx_host={{$dotenv mtx_host}}

@srv_host={{$dotenv srv_host}}

@tenant_url=https://{{tenant_host}}.{{domain}}
@mtx_url=https://{{mtx_host}}.{{domain}}

@token={{$dotenv token}}
@mtx_token={{$dotenv mtx_token}}


### Step 1: fetch CSRF token
### only necessary for requests targetting app router and using session cookie
# @name fetchCsrf
GET {{tenant_url}}/odata/v4/Travel/Flights
x-approuter-authorization: Bearer {{token}}
x-csrf-token: fetch

### Step 2 (auto): extract CSRF token from response
@csrf_token = {{fetchCsrf.response.headers.x-csrf-token}}

### Step 3: test POST
POST {{tenant_url}}/synonymapi/echo
Content-Type: application/json
x-approuter-authorization: Bearer {{token}}
x-csrf-token: {{csrf_token}}

{
  "msg": "calling echo ..."
}



###############################################################################
# reading/manipulating the config table - via app
###############################################################################

# endpoint is not secured, but app router wants authentication -> token required

### directly read the config table
GET {{tenant_url}}/readconf/Registry
x-approuter-authorization: Bearer {{token}}

### read HANA sys view synonyms filtered by app schema
GET {{tenant_url}}/readconf/Synonyms
x-approuter-authorization: Bearer {{token}}

### read status view
GET {{tenant_url}}/readconf/Status
x-approuter-authorization: Bearer {{token}}


### write config table via OData service
POST {{tenant_url}}/readconf/Registry
Content-Type: application/json
Accept: application/json
x-approuter-authorization: Bearer {{token}}
#x-csrf-token: {{csrf_token}}

{
  "srv": "sap.capire.flights.FlightsService_syn", "target": "xflights-db"
}



###
POST {{tenant_url}}/synonymapi/echo
Content-Type: application/json
x-approuter-authorization: Bearer {{token}}
#x-csrf-token: {{csrf_token}}

{
  "msg": "calling echo in app"
}

###
POST {{tenant_url}}/synonymapi/getConfig
Content-Type: application/json
x-approuter-authorization: Bearer {{token}}
#x-csrf-token: {{csrf_token}}

###
POST {{tenant_url}}/synonymapi/check
Content-Type: application/json
x-approuter-authorization: Bearer {{token}}
#x-csrf-token: {{csrf_token}}

{
  "srv": "sap.capire.flights.FlightsService_syn"
}

###
POST {{tenant_url}}/synonymapi/setDynamicConfig
Content-Type: application/json
x-approuter-authorization: Bearer {{token}}
#x-csrf-token: {{csrf_token}}

{
  "srv": "sap.capire.flights.FlightsService_syn", "target": "xflights-db"
}

###
POST {{tenant_url}}/synonymapi/deleteDynamicConfig
Content-Type: application/json
x-approuter-authorization: Bearer {{token}}
#x-csrf-token: {{csrf_token}}

{
  "srv": "sap.capire.flights.FlightsService_syn"
}



###############################################################################
# reading/manipulating the config table - via mtx
###############################################################################

# currently endpoint /-/cds/readconf is not secured
# -> no token necessary

### directly read the config table
GET {{mtx_url}}/-/cds/readconf/Registry(tenant='{{tenant_id}}')/Set
#x-approuter-authorization: Bearer {{token}}

### read HANA sys view synonyms filtered by app schema
GET {{mtx_url}}/-/cds/readconf/Synonyms(tenant='{{tenant_id}}')/Set
#x-approuter-authorization: Bearer {{token}}

### read status view
GET {{mtx_url}}/-/cds/readconf/Status(tenant='{{tenant_id}}')/Set
#x-approuter-authorization: Bearer {{token}}



###
POST {{mtx_url}}/-/cds/synonymapi/echo
Content-Type: application/json
#x-approuter-authorization: Bearer {{token}}
#x-csrf-token: {{csrf_token}}

{
  "msg": "calling echo in mtx via tenant_url"
}

###
POST {{mtx_url}}/-/cds/synonymapi/getConfig
Content-Type: application/json
#x-approuter-authorization: Bearer {{token}}
#x-csrf-token: {{csrf_token}}

{
  "tenant": "{{tenant_id}}"
}

###
POST {{mtx_url}}/-/cds/synonymapi/check
Content-Type: application/json
#x-approuter-authorization: Bearer {{token}}
#x-csrf-token: {{csrf_token}}

{
  "tenant": "{{tenant_id}}",
  "srv": "sap.capire.flights.FlightsService_syn"
}

###
POST {{mtx_url}}/-/cds/synonymapi/setDynamicConfig
Content-Type: application/json
#x-approuter-authorization: Bearer {{token}}
#x-csrf-token: {{csrf_token}}

{
  "tenant": "{{tenant_id}}",
  "srv": "sap.capire.flights.FlightsService_syn",
  "target": "xflights-db",
  "triggerUpgrade": true
}

###
POST {{mtx_url}}/-/cds/synonymapi/deleteDynamicConfig
Content-Type: application/json
#x-approuter-authorization: Bearer {{token}}
#x-csrf-token: {{csrf_token}}

{
  "tenant": "{{tenant_id}}",
  "srv": "sap.capire.flights.FlightsService_syn",
  "triggerUpgrade": true
}


###############################################################################
# mtx
###############################################################################


### Get app URL
GET {{mtx_url}}/-/cds/saas-provisioning/getAppUrl
Authorization: Bearer {{mtx_token}}


### Get all metadata
GET {{mtx_url}}/-/cds/saas-provisioning/tenant
Authorization: Bearer {{mtx_token}}


### upgrade * (async)
# @name upgrade
POST {{mtx_url}}/-/cds/saas-provisioning/upgrade
Content-Type: application/json
Authorization: Bearer {{mtx_token}}

{
    "tenants": ["*"]
}

### poll upgrade job status (copy job ID from upgrade response's location header)
GET {{mtx_url}}/-/cds/jobs/pollJob(ID='{{upgrade.response.headers.x-job-id}}')
Authorization: Bearer {{mtx_token}}

